# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# https://nvidia.github.io/libnvidia-container/
---
- name: set facts
  set_fact:
    dist_id: "{{ ansible_distribution | lower }}{{ ansible_distribution_version }}"
- name: stat libnvidia-container-gpgkey.pem
  stat:
    path: /root/libnvidia-container-gpgkey.pem
  register: st_pgpkey
- name: copy/install pgpkey
  block:
    - name: install pgp key
      copy:
        src: libnvidia-container.pub.pem
        dest: /root/libnvidia-container-gpgkey.pem
        mode: '0640'
        owner: root
        group: root
      register: gpgkey

    - name: import pgp key
      shell:
        apt-key add /root/libnvidia-container-gpgkey.pem
      when: gpgkey.changed
  when: not (st_pgpkey.stat.islnk is defined)
#- name: fetch pgp key
#  fetch:
#    src: https://nvidia.github.io/libnvidia-container/gpgkey
#    dest: /root/libnvidia-container-gpgkey.pem
#  register: gpgkey

- name: stat libnvidia-container.list
  stat:
    path: /etc/apt/sources.list.d/libnvidia-container.list
  register: st_repolist
- name: copy/install repo file
  block:
  - name: download CUDA local installer
    get_url:
      url: "https://nvidia.github.io/libnvidia-container/{{ dist_id }}/libnvidia-container.list"
      dest: "/etc/apt/sources.list.d/libnvidia-container.list"
    register: repo_list
#  - name: fetch repo.list
#    shell: |
#      wget -q -O /etc/apt/sources.list.d/libnvidia-container.list \
#           https://nvidia.github.io/libnvidia-container/{{ dist_id }}/libnvidia-container.list
#    args:
#      creates: /etc/apt/sources.list.d/libnvidia-container.list
#    register: repo_list

  when: not (st_repolist.stat.islnk is defined)

